export type IntegrationConnectType = "apiKey" | "oauth";

export type IntegrationField = {
  name: string;
  label: string;
  type: "text" | "password" | "url";
  placeholder?: string;
  required?: boolean;
};

export type IntegrationCatalogItem = {
  provider: string;
  category: string;
  displayName: string;
  description: string;
  connectType: IntegrationConnectType;
  credentialSchema: IntegrationField[];
  logoText: string;
  badgeClass: string;
};

export const integrationsCatalog: IntegrationCatalogItem[] = [
  {
    provider: "telnyx",
    category: "Telephony",
    displayName: "Telnyx",
    description: "Voice, SMS, and AI assistant telephony APIs.",
    connectType: "apiKey",
    credentialSchema: [
      { name: "apiKey", label: "API Key", type: "password", required: true },
      { name: "messagingProfileId", label: "Messaging Profile ID", type: "text" },
    ],
    logoText: "T",
    badgeClass: "bg-red-100 text-red-700 dark:bg-red-500/15 dark:text-red-300",
  },
  {
    provider: "twilio",
    category: "Telephony",
    displayName: "Twilio",
    description: "Voice and SMS for outbound calling and messaging.",
    connectType: "apiKey",
    credentialSchema: [
      { name: "accountSid", label: "Account SID", type: "text", required: true },
      { name: "authToken", label: "Auth Token", type: "password", required: true },
    ],
    logoText: "TW",
    badgeClass: "bg-blue-100 text-blue-700 dark:bg-blue-500/15 dark:text-blue-300",
  },
  {
    provider: "openai",
    category: "AI Providers",
    displayName: "OpenAI",
    description: "Core LLM provider for assistants and content generation.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "O",
    badgeClass: "bg-emerald-100 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300",
  },
  {
    provider: "abacus",
    category: "AI Providers",
    displayName: "Abacus.AI",
    description: "ChatLLM, Super Assistants, and Deep Agent integrations.",
    connectType: "apiKey",
    credentialSchema: [
      { name: "apiKey", label: "API Key", type: "password", required: true },
      { name: "baseUrl", label: "API Base URL", type: "url" },
    ],
    logoText: "AB",
    badgeClass: "bg-fuchsia-100 text-fuchsia-700 dark:bg-fuchsia-500/15 dark:text-fuchsia-300",
  },
  {
    provider: "ai_gateway",
    category: "AI Providers",
    displayName: "Vercel AI Gateway",
    description: "Unified model routing with centralized cost and model controls.",
    connectType: "apiKey",
    credentialSchema: [
      { name: "apiKey", label: "Gateway API Key", type: "password", required: true },
      { name: "baseUrl", label: "Gateway Base URL", type: "url" },
    ],
    logoText: "AG",
    badgeClass: "bg-slate-100 text-slate-700 dark:bg-slate-500/15 dark:text-slate-300",
  },
  {
    provider: "anthropic",
    category: "AI Providers",
    displayName: "Anthropic",
    description: "Claude models for reasoning and long-form responses.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "A",
    badgeClass: "bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300",
  },
  {
    provider: "google-gemini",
    category: "AI Providers",
    displayName: "Google Gemini",
    description: "Gemini models for multimodal AI capabilities.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "G",
    badgeClass: "bg-yellow-100 text-yellow-700 dark:bg-yellow-500/15 dark:text-yellow-300",
  },
  {
    provider: "vapi",
    category: "Voice / Agents",
    displayName: "Vapi",
    description: "Voice agent platform for outbound and inbound calling.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "V",
    badgeClass: "bg-indigo-100 text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300",
  },
  {
    provider: "resemble",
    category: "Voice / Agents",
    displayName: "Resemble AI",
    description: "Expressive TTS and voice cloning for premium voice agents.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "RZ",
    badgeClass: "bg-purple-100 text-purple-700 dark:bg-purple-500/15 dark:text-purple-300",
  },
  {
    provider: "elevenlabs",
    category: "Voice / Agents",
    displayName: "ElevenLabs",
    description: "High-quality voice synthesis for AI agents.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "EL",
    badgeClass: "bg-sky-100 text-sky-700 dark:bg-sky-500/15 dark:text-sky-300",
  },
  {
    provider: "assemblyai",
    category: "Voice / Agents",
    displayName: "AssemblyAI",
    description: "Realtime and post-call speech intelligence for summaries and QA.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "AA",
    badgeClass: "bg-emerald-100 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300",
  },
  {
    provider: "deepgram",
    category: "Voice / Agents",
    displayName: "Deepgram",
    description: "Speech-to-text and speech intelligence.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "D",
    badgeClass: "bg-teal-100 text-teal-700 dark:bg-teal-500/15 dark:text-teal-300",
  },
  {
    provider: "gohighlevel",
    category: "CRM",
    displayName: "GoHighLevel",
    description: "Primary CRM integration for lead and pipeline sync.",
    connectType: "apiKey",
    credentialSchema: [
      { name: "apiKey", label: "API Key", type: "password", required: true },
      { name: "locationId", label: "Location ID", type: "text", required: true },
    ],
    logoText: "GHL",
    badgeClass: "bg-orange-100 text-orange-700 dark:bg-orange-500/15 dark:text-orange-300",
  },
  {
    provider: "hubspot",
    category: "CRM",
    displayName: "HubSpot",
    description: "CRM and marketing automation.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "Private App Token", type: "password" }],
    logoText: "H",
    badgeClass: "bg-rose-100 text-rose-700 dark:bg-rose-500/15 dark:text-rose-300",
  },
  {
    provider: "salesforce",
    category: "CRM",
    displayName: "Salesforce",
    description: "Enterprise CRM and pipeline management.",
    connectType: "oauth",
    credentialSchema: [],
    logoText: "SF",
    badgeClass: "bg-blue-100 text-blue-700 dark:bg-blue-500/15 dark:text-blue-300",
  },
  {
    provider: "pipedrive",
    category: "CRM",
    displayName: "Pipedrive",
    description: "Sales CRM for pipeline visibility.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiToken", label: "API Token", type: "password", required: true }],
    logoText: "P",
    badgeClass: "bg-lime-100 text-lime-700 dark:bg-lime-500/15 dark:text-lime-300",
  },
  {
    provider: "google-calendar",
    category: "Scheduling",
    displayName: "Google Calendar",
    description: "Calendar sync for bookings and reminders.",
    connectType: "oauth",
    credentialSchema: [],
    logoText: "GC",
    badgeClass: "bg-amber-100 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300",
  },
  {
    provider: "calcom",
    category: "Scheduling",
    displayName: "Cal.com",
    description: "Flexible scheduling workflows and hosted booking links.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "CC",
    badgeClass: "bg-zinc-200 text-zinc-700 dark:bg-zinc-700 dark:text-zinc-200",
  },
  {
    provider: "nylas",
    category: "Scheduling",
    displayName: "Nylas",
    description: "Enterprise calendaring and scheduling APIs across providers.",
    connectType: "apiKey",
    credentialSchema: [
      { name: "apiKey", label: "API Key", type: "password", required: true },
      { name: "apiUri", label: "API URI", type: "url" },
    ],
    logoText: "NY",
    badgeClass: "bg-indigo-100 text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300",
  },
  {
    provider: "calendly",
    category: "Scheduling",
    displayName: "Calendly",
    description: "Scheduling automation and booking links.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "C",
    badgeClass: "bg-cyan-100 text-cyan-700 dark:bg-cyan-500/15 dark:text-cyan-300",
  },
  {
    provider: "wasabi",
    category: "Storage / Data Vault",
    displayName: "Wasabi",
    description: "External object storage for agent knowledge and archival data.",
    connectType: "apiKey",
    credentialSchema: [
      { name: "accessKeyId", label: "Access Key ID", type: "password", required: true },
      { name: "secretAccessKey", label: "Secret Access Key", type: "password", required: true },
      { name: "bucket", label: "Default Bucket", type: "text" },
      { name: "region", label: "Region", type: "text" },
      { name: "endpoint", label: "Endpoint URL", type: "url" },
    ],
    logoText: "W",
    badgeClass: "bg-amber-100 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300",
  },
  {
    provider: "meta-ads",
    category: "Ads / Acquisition",
    displayName: "Meta Ads",
    description: "Facebook and Instagram advertising.",
    connectType: "oauth",
    credentialSchema: [],
    logoText: "M",
    badgeClass: "bg-indigo-100 text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300",
  },
  {
    provider: "google-ads",
    category: "Ads / Acquisition",
    displayName: "Google Ads",
    description: "Search and display ads reporting.",
    connectType: "oauth",
    credentialSchema: [],
    logoText: "GA",
    badgeClass: "bg-yellow-100 text-yellow-700 dark:bg-yellow-500/15 dark:text-yellow-300",
  },
  {
    provider: "tiktok-ads",
    category: "Ads / Acquisition",
    displayName: "TikTok Ads",
    description: "Short-form acquisition campaigns.",
    connectType: "oauth",
    credentialSchema: [],
    logoText: "TT",
    badgeClass: "bg-gray-200 text-gray-700 dark:bg-gray-700 dark:text-gray-200",
  },
  {
    provider: "facebook-pages",
    category: "Social / Messaging",
    displayName: "Facebook Pages",
    description: "Page messaging and engagement.",
    connectType: "oauth",
    credentialSchema: [],
    logoText: "FB",
    badgeClass: "bg-blue-100 text-blue-700 dark:bg-blue-500/15 dark:text-blue-300",
  },
  {
    provider: "instagram",
    category: "Social / Messaging",
    displayName: "Instagram",
    description: "Social engagement and inbox sync.",
    connectType: "oauth",
    credentialSchema: [],
    logoText: "IG",
    badgeClass: "bg-pink-100 text-pink-700 dark:bg-pink-500/15 dark:text-pink-300",
  },
  {
    provider: "whatsapp-business",
    category: "Social / Messaging",
    displayName: "WhatsApp Business",
    description: "Business messaging for support and leads.",
    connectType: "oauth",
    credentialSchema: [],
    logoText: "WA",
    badgeClass: "bg-green-100 text-green-700 dark:bg-green-500/15 dark:text-green-300",
  },
  {
    provider: "zapier",
    category: "Automation / Webhooks",
    displayName: "Zapier",
    description: "Workflow automation triggers and actions.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password" }],
    logoText: "Z",
    badgeClass: "bg-orange-100 text-orange-700 dark:bg-orange-500/15 dark:text-orange-300",
  },
  {
    provider: "make",
    category: "Automation / Webhooks",
    displayName: "Make (Integromat)",
    description: "Scenario-based automation and webhooks.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password" }],
    logoText: "M",
    badgeClass: "bg-purple-100 text-purple-700 dark:bg-purple-500/15 dark:text-purple-300",
  },
  {
    provider: "webhooks",
    category: "Automation / Webhooks",
    displayName: "Generic Webhooks",
    description: "Shared signing secret for outgoing webhooks.",
    connectType: "apiKey",
    credentialSchema: [{ name: "signingSecret", label: "Signing Secret", type: "password" }],
    logoText: "WH",
    badgeClass: "bg-gray-200 text-gray-700 dark:bg-gray-700 dark:text-gray-200",
  },
  {
    provider: "resend",
    category: "Email",
    displayName: "Resend",
    description: "Transactional email provider.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "R",
    badgeClass: "bg-zinc-200 text-zinc-700 dark:bg-zinc-700 dark:text-zinc-200",
  },
  {
    provider: "sendgrid",
    category: "Email",
    displayName: "SendGrid",
    description: "Email API for transactional and marketing sends.",
    connectType: "apiKey",
    credentialSchema: [{ name: "apiKey", label: "API Key", type: "password", required: true }],
    logoText: "SG",
    badgeClass: "bg-blue-100 text-blue-700 dark:bg-blue-500/15 dark:text-blue-300",
  },
  {
    provider: "stripe",
    category: "Payments",
    displayName: "Stripe",
    description: "Subscription billing and payments.",
    connectType: "apiKey",
    credentialSchema: [
      { name: "secretKey", label: "Secret Key", type: "password", required: true },
      { name: "webhookSecret", label: "Webhook Secret", type: "password" },
    ],
    logoText: "S",
    badgeClass: "bg-indigo-100 text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300",
  },
];

export const integrationCategories = Array.from(
  new Set(integrationsCatalog.map((item) => item.category))
);
