-- UK and Western European localities for prefix search (lon -> London, ber -> Berlin, etc.)
-- Cities with Telnyx inventory. Enables same pattern as US: type partial, get suggestions.
INSERT INTO telnyx_localities (country_code, locality, phone_number_type, source)
VALUES
  -- United Kingdom (GB)
  ('GB', 'London', 'local', 'telnyx'),
  ('GB', 'Manchester', 'local', 'telnyx'),
  ('GB', 'Birmingham', 'local', 'telnyx'),
  ('GB', 'Leeds', 'local', 'telnyx'),
  ('GB', 'Liverpool', 'local', 'telnyx'),
  ('GB', 'Sheffield', 'local', 'telnyx'),
  ('GB', 'Bristol', 'local', 'telnyx'),
  ('GB', 'Edinburgh', 'local', 'telnyx'),
  ('GB', 'Glasgow', 'local', 'telnyx'),
  ('GB', 'Cardiff', 'local', 'telnyx'),
  ('GB', 'Belfast', 'local', 'telnyx'),
  ('GB', 'Newcastle', 'local', 'telnyx'),
  ('GB', 'Nottingham', 'local', 'telnyx'),
  ('GB', 'Southampton', 'local', 'telnyx'),
  -- Ireland (IE)
  ('IE', 'Dublin', 'local', 'telnyx'),
  ('IE', 'Cork', 'local', 'telnyx'),
  ('IE', 'Galway', 'local', 'telnyx'),
  ('IE', 'Limerick', 'local', 'telnyx'),
  -- France (FR)
  ('FR', 'Paris', 'local', 'telnyx'),
  ('FR', 'Lyon', 'local', 'telnyx'),
  ('FR', 'Marseille', 'local', 'telnyx'),
  ('FR', 'Toulouse', 'local', 'telnyx'),
  ('FR', 'Nice', 'local', 'telnyx'),
  ('FR', 'Bordeaux', 'local', 'telnyx'),
  ('FR', 'Lille', 'local', 'telnyx'),
  ('FR', 'Strasbourg', 'local', 'telnyx'),
  -- Germany (DE)
  ('DE', 'Berlin', 'local', 'telnyx'),
  ('DE', 'Munich', 'local', 'telnyx'),
  ('DE', 'München', 'local', 'telnyx'),
  ('DE', 'Hamburg', 'local', 'telnyx'),
  ('DE', 'Cologne', 'local', 'telnyx'),
  ('DE', 'Köln', 'local', 'telnyx'),
  ('DE', 'Frankfurt', 'local', 'telnyx'),
  ('DE', 'Stuttgart', 'local', 'telnyx'),
  ('DE', 'Düsseldorf', 'local', 'telnyx'),
  ('DE', 'Dortmund', 'local', 'telnyx'),
  ('DE', 'Essen', 'local', 'telnyx'),
  -- Spain (ES)
  ('ES', 'Madrid', 'local', 'telnyx'),
  ('ES', 'Barcelona', 'local', 'telnyx'),
  ('ES', 'Valencia', 'local', 'telnyx'),
  ('ES', 'Seville', 'local', 'telnyx'),
  ('ES', 'Sevilla', 'local', 'telnyx'),
  ('ES', 'Bilbao', 'local', 'telnyx'),
  ('ES', 'Malaga', 'local', 'telnyx'),
  ('ES', 'Málaga', 'local', 'telnyx'),
  -- Italy (IT)
  ('IT', 'Rome', 'local', 'telnyx'),
  ('IT', 'Roma', 'local', 'telnyx'),
  ('IT', 'Milan', 'local', 'telnyx'),
  ('IT', 'Milano', 'local', 'telnyx'),
  ('IT', 'Naples', 'local', 'telnyx'),
  ('IT', 'Napoli', 'local', 'telnyx'),
  ('IT', 'Turin', 'local', 'telnyx'),
  ('IT', 'Torino', 'local', 'telnyx'),
  ('IT', 'Florence', 'local', 'telnyx'),
  ('IT', 'Firenze', 'local', 'telnyx'),
  ('IT', 'Venice', 'local', 'telnyx'),
  ('IT', 'Venezia', 'local', 'telnyx'),
  ('IT', 'Bologna', 'local', 'telnyx'),
  -- Netherlands (NL)
  ('NL', 'Amsterdam', 'local', 'telnyx'),
  ('NL', 'Rotterdam', 'local', 'telnyx'),
  ('NL', 'The Hague', 'local', 'telnyx'),
  ('NL', 'Den Haag', 'local', 'telnyx'),
  ('NL', 'Utrecht', 'local', 'telnyx'),
  ('NL', 'Eindhoven', 'local', 'telnyx'),
  -- Belgium (BE)
  ('BE', 'Brussels', 'local', 'telnyx'),
  ('BE', 'Antwerp', 'local', 'telnyx'),
  ('BE', 'Ghent', 'local', 'telnyx'),
  -- Austria (AT)
  ('AT', 'Vienna', 'local', 'telnyx'),
  ('AT', 'Graz', 'local', 'telnyx'),
  ('AT', 'Linz', 'local', 'telnyx'),
  -- Switzerland (CH)
  ('CH', 'Zurich', 'local', 'telnyx'),
  ('CH', 'Geneva', 'local', 'telnyx'),
  ('CH', 'Basel', 'local', 'telnyx'),
  ('CH', 'Bern', 'local', 'telnyx'),
  ('CH', 'Lausanne', 'local', 'telnyx'),
  -- Portugal (PT)
  ('PT', 'Lisbon', 'local', 'telnyx'),
  ('PT', 'Lisboa', 'local', 'telnyx'),
  ('PT', 'Porto', 'local', 'telnyx'),
  ('PT', 'Braga', 'local', 'telnyx'),
  -- Luxembourg (LU)
  ('LU', 'Luxembourg', 'local', 'telnyx'),
  -- Nordic
  ('SE', 'Stockholm', 'local', 'telnyx'),
  ('SE', 'Gothenburg', 'local', 'telnyx'),
  ('SE', 'Malmö', 'local', 'telnyx'),
  ('NO', 'Oslo', 'local', 'telnyx'),
  ('NO', 'Bergen', 'local', 'telnyx'),
  ('DK', 'Copenhagen', 'local', 'telnyx'),
  ('DK', 'Aarhus', 'local', 'telnyx'),
  ('FI', 'Helsinki', 'local', 'telnyx'),
  ('FI', 'Tampere', 'local', 'telnyx')
ON CONFLICT (country_code, locality, phone_number_type, source) DO NOTHING;
